import { applications as mockApplications, dashboardStats, notifications as mockNotifications, rpaStatus } from '../data/mockData'
import type { ApiScholarship, ApiScholarshipApplication, Application, DashboardStatistics, Document, EligibilityResult, Notification, RPAStatus, Scholarship, ScholarshipApplication, Student, User } from '../types'
import { getCurrentStudentId } from './session'

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8000/api').replace(/\/$/, '')

export class ApiError extends Error {
  status: number
  constructor(message: string, status: number) { super(message); this.name = 'ApiError'; this.status = status }
}

interface BackendStudent { id: number; name: string; email: string; phone?: string; course?: string; academic_score?: number; city?: string; academic_year?: string; email_updates?: boolean; scholarship_suggestions?: boolean; created_at: string }
interface BackendDocument { id: number; application_id?: number; student_id?: number; name: string; document_type?: string; file_name?: string; original_filename?: string; stored_filename?: string; file_path?: string; file_type?: string; file_size?: number; upload_date?: string; status: string; verification_status?: string; remarks?: string; uploaded_at?: string; extracted_text?: string; ocr_status?: string; ocr_processed_at?: string; matched_fields?: string; mismatched_fields?: string }
interface BackendApplication { id: number; application_number: string; student_id: number; course: string; status: Application['status']; submitted_at?: string; remarks?: string; created_at: string; student?: BackendStudent; documents: BackendDocument[] }
interface BackendNotification { id: number; student_id: number; title: string; message: string; notification_type: Notification['type']; read: boolean; created_at: string }
interface BackendOCRResult { document_id: number; ocr_status: string; verification_status: string; extracted_text: string; matched_fields: string[]; mismatched_fields: string[]; remarks: string; processed_at?: string }
interface BackendScholarship { id: number; name: string; scheme_name?: string; description?: string; provider: string; eligibility_summary?: string; eligibility_rules: Record<string, unknown> | string; required_documents: string[] | string; application_start_date?: string; application_end_date?: string; amount_or_benefit?: string; status: string; is_active: boolean; created_at?: string; updated_at?: string }
interface BackendScholarshipApplication { id: number; student_id: number; scholarship_id: number; eligibility_status: string; verification_status: string; application_status: string; remarks?: string; applied_at?: string; updated_at?: string; submitted_at?: string }
interface BackendEligibilityResult { student_id: number; scholarship_id: number; eligibility_status: string; matched_rules: string[]; unmatched_rules: string[]; missing_information: string[]; required_documents: string[]; available_documents: string[]; missing_documents: string[]; remarks: string }

async function fetchWithLocalSession(url: string, options: RequestInit = {}, includeJsonContentType = true): Promise<Response> {
  const headers = new Headers(options.headers)
  if (includeJsonContentType && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json')

  const sessionId = window.localStorage.getItem('admitflow.studentId')
  if (sessionId && !headers.has('X-Student-ID')) headers.set('X-Student-ID', sessionId)

  return fetch(url, { ...options, headers })
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  let response: Response
  try { response = await fetchWithLocalSession(`${API_BASE_URL}${path}`, options) } catch (error) { if (error instanceof ApiError) throw error; throw new ApiError('The backend is unavailable. Start FastAPI and try again.', 0) }
  if (!response.ok) { let detail = `Request failed with status ${response.status}`; try { const body = await response.json() as { detail?: string }; detail = body.detail ?? detail } catch { /* response may not contain JSON */ } console.error('API request failed', { path, status: response.status, detail }); throw new ApiError(detail, response.status) }
  return response.json() as Promise<T>
}

function mapVerificationStatus(status: string): Document['verification']['status'] { return status.replace('_', '-') as Document['verification']['status'] }
function mapOCRResult(result: BackendOCRResult): BackendOCRResult { return { ...result, verification_status: result.verification_status.replace('_', '-') } }
function mapDocument(document: BackendDocument): Document { return { id: String(document.id), name: document.document_type ?? document.name, required: true, studentId: document.student_id ? String(document.student_id) : undefined, applicationId: document.application_id ? String(document.application_id) : undefined, fileName: document.file_name, originalFilename: document.original_filename, storedFilename: document.stored_filename, filePath: document.file_path, fileType: document.file_type, fileSize: document.file_size, uploadedAt: document.upload_date ?? document.uploaded_at, ocrStatus: document.ocr_status, extractedText: document.extracted_text, matchedFields: document.matched_fields ? JSON.parse(document.matched_fields) : [], mismatchedFields: document.mismatched_fields ? JSON.parse(document.mismatched_fields) : [], verification: { status: mapVerificationStatus(document.verification_status || document.status || 'pending'), remarks: document.remarks } } }
function mapStudent(student: BackendStudent): Student { return { id: String(student.id), userId: String(student.id), name: student.name, email: student.email, phone: student.phone ?? '', course: student.course ?? '', academicScore: student.academic_score ?? 0, city: student.city ?? '', academicYear: student.academic_year ?? '', emailUpdates: student.email_updates ?? true, scholarshipSuggestions: student.scholarship_suggestions ?? true } }
function mapApplication(application: BackendApplication): Application { if (!application.student) throw new ApiError('Application is missing its student record.', 500); const student = mapStudent(application.student); return { id: application.application_number, student, course: application.course, submittedAt: application.submitted_at ? new Date(application.submitted_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : undefined, documentSummary: `${application.documents.filter(item => item.status === 'verified').length} verified, ${application.documents.filter(item => item.status === 'pending').length} pending`, status: application.status, documents: application.documents.map(mapDocument), timeline: [{ label: 'Application Submitted', date: application.submitted_at ?? 'Not submitted', status: application.submitted_at ? 'complete' : 'current' }, { label: 'Document Verification', date: 'In progress', status: 'current' }, { label: 'Academic Verification', status: 'upcoming' }, { label: 'Admission Review', status: 'upcoming' }, { label: 'Final Decision', status: 'upcoming' }] } }
function mapNotification(notification: BackendNotification): Notification { return { id: String(notification.id), title: notification.title, message: notification.message, type: notification.notification_type, date: new Date(notification.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), read: notification.read } }
function jsonValue<T>(value: T | string, fallback: T): T { if (typeof value !== 'string') return value; try { return JSON.parse(value) as T } catch { return fallback } }
function mapScholarship(item: BackendScholarship): ApiScholarship { return { id: item.id, name: item.name, schemeName: item.scheme_name ?? item.name, description: item.description ?? '', provider: item.provider, eligibilitySummary: item.eligibility_summary ?? '', eligibilityRules: jsonValue(item.eligibility_rules, {}), requiredDocuments: jsonValue(item.required_documents, []), applicationStartDate: item.application_start_date, applicationEndDate: item.application_end_date, amountOrBenefit: item.amount_or_benefit ?? '', status: item.status, isActive: item.is_active, createdAt: item.created_at, updatedAt: item.updated_at } }
function mapScholarshipApplication(item: BackendScholarshipApplication): ApiScholarshipApplication { return { id: item.id, studentId: item.student_id, scholarshipId: item.scholarship_id, eligibilityStatus: item.eligibility_status, verificationStatus: item.verification_status, applicationStatus: item.application_status, remarks: item.remarks, appliedAt: item.applied_at ?? item.submitted_at, updatedAt: item.updated_at } }
function mapEligibility(item: BackendEligibilityResult): EligibilityResult { return { studentId: item.student_id, scholarshipId: item.scholarship_id, eligibilityStatus: item.eligibility_status, matchedRules: item.matched_rules, unmatchedRules: item.unmatched_rules, missingInformation: item.missing_information, requiredDocuments: item.required_documents, availableDocuments: item.available_documents, missingDocuments: item.missing_documents, remarks: item.remarks } }

export const api = {
  async login(email: string, password = ''): Promise<User> { return request<User>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }) },
  async firebaseSession(): Promise<{ registered: boolean; role: 'student' | 'admin'; firebase_uid: string; email: string; name: string; student_id?: number }> { return request('/auth/firebase/session') },
  async firebaseOnboard(payload: { name: string; phone: string; course: string; academicYear: string }): Promise<Student> { return mapStudent(await request<BackendStudent>('/auth/firebase/onboard', { method: 'POST', body: JSON.stringify({ name: payload.name, phone: payload.phone, course: payload.course, academic_year: payload.academicYear }) })) },
  async createStudent(payload: Pick<Student, 'name' | 'email' | 'phone' | 'course' | 'academicScore' | 'city' | 'academicYear'> & { password?: string }): Promise<Student> { return mapStudent(await request<BackendStudent>('/students', { method: 'POST', body: JSON.stringify({ name: payload.name, email: payload.email, phone: payload.phone, course: payload.course, academic_score: payload.academicScore, city: payload.city, academic_year: payload.academicYear, password: payload.password }) })) },
  async getStudent(id: number): Promise<Student> { return mapStudent(await request<BackendStudent>(`/students/${id}`)) },
  async updateStudent(id: number, payload: Partial<Pick<Student, 'name' | 'email' | 'phone' | 'course' | 'academicScore' | 'city' | 'academicYear' | 'emailUpdates' | 'scholarshipSuggestions'>>): Promise<Student> { return mapStudent(await request<BackendStudent>(`/students/${id}`, { method: 'PATCH', body: JSON.stringify({ name: payload.name, email: payload.email, phone: payload.phone, course: payload.course, academic_score: payload.academicScore, city: payload.city, academic_year: payload.academicYear, email_updates: payload.emailUpdates, scholarship_suggestions: payload.scholarshipSuggestions }) })) },
  async createApplication(payload: { studentId: number; course: string; status?: Application['status']; submittedAt?: string }): Promise<Application> { const result = await request<BackendApplication>('/applications', { method: 'POST', body: JSON.stringify({ student_id: payload.studentId, course: payload.course, status: payload.status ?? 'draft', submitted_at: payload.submittedAt }) }); window.localStorage.setItem('admitflow.applicationId', String(result.id)); return mapApplication(result) },
  async getApplications(): Promise<Application[]> { const result = await request<BackendApplication[]>('/applications'); return result.map(mapApplication) },
    async getStudentApplications(studentId = getCurrentStudentId()): Promise<Application[]> { const result = await request<BackendApplication[]>(`/applications/student/${studentId}`); return result.map(mapApplication) },
  async getApplicationById(id: string | number): Promise<Application> { const backendId = typeof id === 'string' && id.startsWith('ADM') ? (await request<BackendApplication[]>('/applications')).find(item => item.application_number === id)?.id : id; if (!backendId) throw new ApiError('Application not found.', 404); const result = await request<BackendApplication>(`/applications/${backendId}`); return mapApplication(result) },
  async updateApplicationStatus(id: string | number, status: Application['status']): Promise<Application> { const backendId = typeof id === 'string' && id.startsWith('ADM') ? (await request<BackendApplication[]>('/applications')).find(item => item.application_number === id)?.id : id; if (!backendId) throw new ApiError('Application not found.', 404); const result = await request<BackendApplication>(`/applications/${backendId}`, { method: 'PATCH', body: JSON.stringify({ status }) }); return mapApplication(result) },
  async createDocumentRecord(applicationId: number, name: string, fileName?: string): Promise<Document> { const result = await request<BackendDocument>('/documents', { method: 'POST', body: JSON.stringify({ application_id: applicationId, name, file_name: fileName, status: fileName ? 'pending' : 'missing' }) }); return mapDocument(result) },
  async getDocuments(applicationId?: number): Promise<Document[]> { if (applicationId === undefined) return this.getStudentDocuments(); const result = await request<BackendDocument[]>(`/documents?application_id=${applicationId}`); return result.map(mapDocument) },
  async getStudentDocuments(studentId = getCurrentStudentId()): Promise<Document[]> { const result = await request<BackendDocument[]>(`/documents/student/${studentId}`); return result.map(mapDocument) },
  async getAllDocuments(): Promise<Document[]> { const result = await request<BackendDocument[]>('/documents'); return result.map(mapDocument) },
  async uploadDocumentFile(studentId: number, documentType: string, file: File): Promise<Document> { const form = new FormData(); form.append('student_id', String(studentId)); form.append('document_type', documentType); form.append('file', file); let response: Response; try { response = await fetchWithLocalSession(`${API_BASE_URL}/documents/upload`, { method: 'POST', body: form }, false) } catch { throw new ApiError('The backend is unavailable. Start FastAPI and try again.', 0) } if (!response.ok) { let detail = `Upload failed with status ${response.status}`; try { const body = await response.json() as { detail?: string }; detail = body.detail ?? detail } catch { /* response may not contain JSON */ } throw new ApiError(detail, response.status) } return mapDocument(await response.json() as BackendDocument) },
  async deleteDocument(id: string | number): Promise<void> { const response = await fetchWithLocalSession(`${API_BASE_URL}/documents/${id}`, { method: 'DELETE' }, false); if (!response.ok) { let detail = `Delete failed with status ${response.status}`; try { const body = await response.json() as { detail?: string }; detail = body.detail ?? detail } catch { /* response may not contain JSON */ } throw new ApiError(detail, response.status) } },
  getDocumentDownloadUrl(id: string | number): string { return `${API_BASE_URL}/documents/${id}/download` },
  async updateDocumentVerificationStatus(id: string | number, status: Document['verification']['status'], remarks?: string): Promise<Document> { const result = await request<BackendDocument>(`/documents/${id}`, { method: 'PATCH', body: JSON.stringify({ status, remarks }) }); return mapDocument(result) },
  async runDocumentOCR(id: string | number): Promise<BackendOCRResult> { return mapOCRResult(await request<BackendOCRResult>(`/documents/${id}/ocr`, { method: 'POST' })) },
  async verifyDocument(id: string | number): Promise<BackendOCRResult> { return mapOCRResult(await request<BackendOCRResult>(`/documents/${id}/verify`, { method: 'POST' })) },
  async getDocumentVerification(id: string | number): Promise<BackendOCRResult> { return mapOCRResult(await request<BackendOCRResult>(`/documents/${id}/verification`)) },
  async getStudentDashboard(studentId = getCurrentStudentId()): Promise<{ student: Student; application: Application | null; documents: Document[]; notifications: Notification[]; scholarships: ApiScholarship[]; deadlines: string[] }> { const [student, applicationList, documents, backendNotifications, scholarships] = await Promise.all([this.getStudent(studentId), this.getStudentApplications(studentId), this.getStudentDocuments(studentId), this.getNotifications(studentId), this.getScholarships()]); const application = applicationList[0] ?? null; return { student, application, documents, notifications: backendNotifications, scholarships, deadlines: scholarships.filter(item => item.isActive).map(item => `${item.schemeName} · ${item.applicationEndDate ? new Date(item.applicationEndDate).toLocaleDateString() : 'No deadline'}`) } },
  async getNotifications(studentId = getCurrentStudentId()): Promise<Notification[]> { const result = await request<BackendNotification[]>(`/students/${studentId}/notifications`); return result.map(mapNotification) },
  async markNotificationRead(id: string | number): Promise<Notification> { return mapNotification(await request<BackendNotification>(`/notifications/${id}/read`, { method: 'PATCH' })) },
  async markAllNotificationsRead(studentId = getCurrentStudentId()): Promise<Notification[]> { const result = await request<BackendNotification[]>(`/notifications/student/${studentId}/read-all`, { method: 'PATCH' }); return result.map(mapNotification) },
  async getAdminStatistics(): Promise<{ stats: DashboardStatistics; rpa: RPAStatus }> { const result = await request<{ total_students: number; total_applications: number; pending_documents: number; manual_documents: number; scholarship_applications: number; under_review: number; approved: number; rejected: number }>('/applications/statistics'); return { stats: { totalStudents: result.total_students, totalApplications: result.total_applications, pendingVerification: result.pending_documents, verified: result.approved, manualReview: result.manual_documents, rejected: result.rejected, scholarshipApplications: result.scholarship_applications, trend: [], verification: [] }, rpa: { status: 'idle', lastRun: 'Backend queue', applicationsProcessed: result.total_applications, documentsVerified: result.approved } } },
  async getVerificationQueue(): Promise<Document[]> { const result = await request<BackendDocument[]>('/documents'); return result.map(mapDocument) },
  async getScholarships(): Promise<ApiScholarship[]> { return (await request<BackendScholarship[]>('/scholarships')).map(mapScholarship) },
  async getScholarshipById(id: string | number): Promise<ApiScholarship> { return mapScholarship(await request<BackendScholarship>(`/scholarships/${id}`)) },
  async getStudentScholarshipEligibility(studentId = getCurrentStudentId()): Promise<EligibilityResult[]> { return (await request<BackendEligibilityResult[]>(`/students/${studentId}/scholarships/eligibility`)).map(mapEligibility) },
  async getScholarshipEligibility(scholarshipId: string | number, studentId = getCurrentStudentId()): Promise<EligibilityResult> { return mapEligibility(await request<BackendEligibilityResult>(`/scholarships/${scholarshipId}/eligibility/${studentId}`)) },
  async createScholarshipApplication(scholarshipId: number, studentId = getCurrentStudentId()): Promise<ApiScholarshipApplication> { return mapScholarshipApplication(await request<BackendScholarshipApplication>('/scholarship-applications', { method: 'POST', body: JSON.stringify({ scholarship_id: scholarshipId, student_id: studentId }) })) },
  async getStudentScholarshipApplications(studentId = getCurrentStudentId()): Promise<ApiScholarshipApplication[]> { return (await request<BackendScholarshipApplication[]>(`/students/${studentId}/scholarships`)).map(mapScholarshipApplication) },
  async getScholarshipApplications(): Promise<ApiScholarshipApplication[]> { return (await request<BackendScholarshipApplication[]>('/scholarship-applications')).map(mapScholarshipApplication) },
  async getScholarshipApplication(id: string | number): Promise<ApiScholarshipApplication> { return mapScholarshipApplication(await request<BackendScholarshipApplication>(`/scholarship-applications/${id}`)) },
  async updateScholarshipApplication(id: string | number, payload: { eligibilityStatus?: string; verificationStatus?: string; applicationStatus?: string; remarks?: string }): Promise<ApiScholarshipApplication> { return mapScholarshipApplication(await request<BackendScholarshipApplication>(`/scholarship-applications/${id}`, { method: 'PATCH', body: JSON.stringify({ eligibility_status: payload.eligibilityStatus, verification_status: payload.verificationStatus, application_status: payload.applicationStatus, remarks: payload.remarks }) })) },
  async createScholarship(payload: { name: string; provider: string; description: string; eligibilityRules: Record<string, unknown>; requiredDocuments: string[]; amountOrBenefit: string; status: string }): Promise<ApiScholarship> { return mapScholarship(await request<BackendScholarship>('/scholarships', { method: 'POST', body: JSON.stringify({ name: payload.name, provider: payload.provider, description: payload.description, eligibility_rules: payload.eligibilityRules, required_documents: payload.requiredDocuments, amount_or_benefit: payload.amountOrBenefit, status: payload.status }) })) },
  async updateScholarship(id: string | number, payload: Partial<{ name: string; provider: string; description: string; eligibilityRules: Record<string, unknown>; requiredDocuments: string[]; amountOrBenefit: string; status: string }>): Promise<ApiScholarship> { return mapScholarship(await request<BackendScholarship>(`/scholarships/${id}`, { method: 'PATCH', body: JSON.stringify({ name: payload.name, provider: payload.provider, description: payload.description, eligibility_rules: payload.eligibilityRules, required_documents: payload.requiredDocuments, amount_or_benefit: payload.amountOrBenefit, status: payload.status }) })) },
  async applyForScholarship(id: string): Promise<ScholarshipApplication> { const application = await this.createScholarshipApplication(Number(id)); return { id: String(application.id), scholarshipId: id, studentName: '', scholarshipName: `Scholarship ${id}`, eligibilityStatus: application.eligibilityStatus, documentStatus: application.verificationStatus, applicationStatus: application.applicationStatus } },
  async getMockApplications(): Promise<Application[]> { return Promise.resolve(mockApplications) },
  async getMockNotifications(): Promise<Notification[]> { return Promise.resolve(mockNotifications) },
}

export { API_BASE_URL }
