import { type ReactNode } from 'react'
import { Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Clock3, FileText, Menu, Search, X } from 'lucide-react'
import { statusIcon, statusLabel } from '../../utils/format'
import type { ApplicationStatus, Status } from '../../types'

export function Button({ children, variant = 'primary', type = 'button', onClick, className = '', disabled = false }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; type?: 'button' | 'submit'; onClick?: () => void; className?: string; disabled?: boolean }) { return <button type={type} disabled={disabled} onClick={onClick} className={`btn btn-${variant} ${className}`}>{children}</button> }
export function Card({ children, className = '', as = 'section' }: { children: ReactNode; className?: string; as?: 'section' | 'div' }) { const Tag = as; return <Tag className={`card ${className}`}>{children}</Tag> }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'teal' | 'amber' | 'red' | 'green' }) { return <span className={`badge badge-${tone}`}>{children}</span> }
export function StatusBadge({ status }: { status: Status | ApplicationStatus }) { const tone = status === 'verified' || status === 'approved' ? 'green' : status === 'rejected' ? 'red' : status === 'manual-review' ? 'amber' : 'neutral'; return <span className={`status status-${tone}`} aria-label={statusLabel(status)}><span aria-hidden="true">{statusIcon(status)}</span> {statusLabel(status)}</span> }
export function ProgressBar({ value, label }: { value: number; label?: string }) { return <div className="progress-wrap"><div className="progress-meta"><span>{label}</span><strong>{value}%</strong></div><div className="progress-track"><div className="progress-value" style={{ width: `${value}%` }} /></div></div> }
export function SectionHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="section-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="heading">{title}</h2>{description && <p className="muted">{description}</p>}</div>{action}</div> }
export function EmptyState({ title, message }: { title: string; message: string }) { return <div className="empty"><FileText size={28} aria-hidden="true" /><h3>{title}</h3><p>{message}</p></div> }
export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="empty" role="alert"><CircleAlert size={28} aria-hidden="true" /><h3>We couldn't load this yet</h3><p>{message}</p><Button variant="secondary" onClick={onRetry}>Try again</Button></div> }
export function LoadingState() { return <div className="skeleton" role="status" aria-label="Loading"><span /><span /><span /></div> }
export function SearchBar({ value, onChange, placeholder = 'Search' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="search"><Search size={17} aria-hidden="true" /><span className="sr-only">{placeholder}</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /></label> }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title" className="heading">{title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={onClose}><X size={18} /></button></div>{children}</div></div> }
export function ConfirmationDialog({ title, message, onConfirm, onClose }: { title: string; message: string; onConfirm: () => void; onClose: () => void }) { return <Modal title={title} onClose={onClose}><p className="muted">{message}</p><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={onConfirm}>Confirm action</Button></div></Modal> }
export function Stepper({ steps, current }: { steps: string[]; current: number }) { return <nav className="stepper" aria-label="Form progress">{steps.map((step, index) => <div className={`step ${index <= current ? 'step-active' : ''}`} key={step}><span>{index < current ? <Check size={15} /> : index + 1}</span><small>{step}</small></div>)}</nav> }
export function MobileMenuButton({ onClick }: { onClick: () => void }) { return <button className="mobile-menu" aria-label="Open navigation" onClick={onClick}><Menu size={22} /></button> }
export function Toast({ message, onClose }: { message: string; onClose: () => void }) { return <div className="toast" role="status"><Check size={17} aria-hidden="true" /><span>{message}</span><button aria-label="Dismiss notification" onClick={onClose}><X size={15} /></button></div> }
export function Pagination({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) { return <div className="pagination"><Button variant="ghost" onClick={() => onChange(Math.max(1, page - 1))} disabled={page === 1}><ChevronLeft size={16} /> Previous</Button><span>Page {page} of {total}</span><Button variant="ghost" onClick={() => onChange(Math.min(total, page + 1))} disabled={page === total}>Next <ChevronRight size={16} /></Button></div> }
export function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select><ChevronDown className="select-icon" size={16} aria-hidden="true" /></label> }
export function Field({ label, value, onChange, type = 'text', required = false, error, placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; error?: string; placeholder?: string }) { const id = label.toLowerCase().replaceAll(' ', '-'); return <label className="field"><span>{label}{required && <b aria-hidden="true"> *</b>}</span><input id={id} type={type} value={value} required={required} placeholder={placeholder} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={event => onChange(event.target.value)} />{error && <small className="field-error" id={`${id}-error`}><CircleAlert size={14} />{error}</small>}</label> }
export function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><textarea value={value} onChange={event => onChange(event.target.value)} rows={4} /></label> }
export function StatusLegend() { return <div className="status-legend"><StatusBadge status="verified" /><StatusBadge status="pending" /><StatusBadge status="manual-review" /><StatusBadge status="rejected" /><StatusBadge status="missing" /></div> }
export function IconStatus({ type }: { type: 'verified' | 'pending' | 'manual' }) { return type === 'verified' ? <Check size={15} aria-hidden="true" /> : type === 'pending' ? <Clock3 size={15} aria-hidden="true" /> : <CircleAlert size={15} aria-hidden="true" /> }
