import { Navigate, Route, Routes } from 'react-router-dom'
import { PublicLayout } from './layouts/PublicLayout'
import { PortalLayout } from './layouts/PortalLayout'
import { LandingPage, LoginPage, RegisterPage } from './pages/public/Pages'
import { FirebaseLoginPage } from './pages/public/FirebaseLoginPage'
import { FirebaseOnboardingPage } from './pages/public/FirebaseOnboardingPage'
import { AdmissionPage, DocumentsPage, NotificationsPage, ProfilePage, ScholarshipApplyPage, ScholarshipDetailPage, ScholarshipsPage, StatusPage, StudentDashboard } from './pages/student/Pages'
import { RealProfilePage } from './pages/student/RealProfilePage'
import { StudentDashboardPage } from './pages/student/StudentDashboardPage'
import { RealNotificationsPage } from './pages/student/RealNotificationsPage'
import { RealAdmissionPage } from './pages/student/RealAdmissionPage'
import { RealStatusPage } from './pages/student/RealStatusPage'
import { AdminDashboard, AdminApplicationDetail, AdminApplications, AdminReports, AdminSettings, AdminScholarshipApplications, AdminScholarships, VerificationPage } from './pages/admin/Pages'
import { RealAdminDashboard } from './pages/admin/RealAdminDashboard'
import { RealAdminReports } from './pages/admin/RealAdminReports'
import { RealAdminSettings } from './pages/admin/RealAdminSettings'
import { RealAdminScholarshipApplications } from './pages/admin/RealAdminScholarshipApplications'
import { ConnectedAdminApplicationDetail, ConnectedAdminApplications, ConnectedAdmissionPage, ConnectedDocumentsPage, ConnectedNotificationsPage, ConnectedStatusPage, ConnectedStudentDashboard, ConnectedRegisterPage, ConnectedVerificationPage } from './pages/integrated/Pages'
import { ConnectedAdminScholarshipApplicationsPage, ConnectedAdminScholarshipsPage, ConnectedScholarshipApplyPage, ConnectedScholarshipDetailPage, ConnectedScholarshipsPage } from './pages/integrated/ScholarshipPages'
import { RealAdminApplicationDetail, RealDocumentsPage, RealVerificationPage } from './pages/integrated/DocumentPages'

export default function App() { return <Routes><Route element={<PublicLayout />}><Route path="/" element={<LandingPage />} /><Route path="/login" element={<FirebaseLoginPage />} /><Route path="/login/development" element={<LoginPage />} /><Route path="/onboarding" element={<FirebaseOnboardingPage />} /><Route path="/register" element={<Navigate to="/login" replace />} /></Route><Route element={<PortalLayout />}><Route path="/student/dashboard" element={<StudentDashboardPage />} /><Route path="/student/admission" element={<RealAdmissionPage />} /><Route path="/student/documents" element={<RealDocumentsPage />} /><Route path="/student/status" element={<RealStatusPage />} /><Route path="/student/scholarships" element={<ConnectedScholarshipsPage />} /><Route path="/student/scholarships/:id" element={<ConnectedScholarshipDetailPage />} /><Route path="/student/scholarships/:id/apply" element={<ConnectedScholarshipApplyPage />} /><Route path="/student/notifications" element={<RealNotificationsPage />} /><Route path="/student/profile" element={<RealProfilePage />} /></Route><Route element={<PortalLayout admin />}><Route path="/admin/dashboard" element={<RealAdminDashboard />} /><Route path="/admin/applications" element={<ConnectedAdminApplications />} /><Route path="/admin/applications/:id" element={<RealAdminApplicationDetail />} /><Route path="/admin/verification" element={<RealVerificationPage />} /><Route path="/admin/scholarships" element={<ConnectedAdminScholarshipsPage />} /><Route path="/admin/scholarship-applications" element={<RealAdminScholarshipApplications />} /><Route path="/admin/reports" element={<RealAdminReports />} /><Route path="/admin/settings" element={<RealAdminSettings />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
